### ISSUE TITLE
New to BOTs

### ISSUE THREAD

**Issue by wolfie1910** [aparrish/iceboxbreakfast#1]
Hello!

I am a new-be to the BOTs' world.  I am working on Mastodon as part of my univesity project. I setup an instance at my school and I need to evaluate it. Therefore, I am in need of several BOTs to toot at the same time frequently, to be able to generate some traffic.
Any help?

Thank You.

**Comment by aparrish** [comment]
I can only point you to [Mastodon.py](http://mastodonpy.readthedocs.io/en/latest/), a Python library for making Mastodon bots. If you have programming experience, it's fairly straightforward to get something up and running quickly. For more details, you could pose this question on [the #botally slack](http://slack.botally.net/) or the [botmakers slack](https://botmakers.slack.com/messages).
